require 'mongo'
require 'rest-client'
require 'nokogiri'
require 'json'
require 'geokit'

$db = Mongo::Connection.new(ENV["HACKATHON_REROUTE_MONGO_SERVER"], ENV["HACKATHON_REROUTE_MONGO_PORT"])["hackathon_reroute"]
begin
  $auth = $db.authenticate(ENV["HACKATHON_REROUTE_MONGO_USERNAME"], ENV["HACKATHON_REROUTE_MONGO_PASSWORD"])
rescue
  #do nothing for now
end
puts $db

#If you don't have accidents_geocoded.json
#First run rake scrape
#Then run rake geocode
#Finally run rake populate

#If you have accidents_geocoded.json
#Just run rake populate


desc "Scrape for accidents data"
task :scrape do
  f = File.open("accidents.json", "w")
  f.write("[")
  (1..45).to_a.each do |page_count|
    page = RestClient.get "http://secret-taiga-2483.herokuapp.com/data/bike-accidents/raw-data/?page=#{page_count}&date_from=20050101&date_to=20091231&county=87"
    n_page = Nokogiri::HTML.parse(page)

    header = n_page.css("thead").children[0]

    n_page.css("#raw-data-table tbody tr").each do |row|
      accident = {}
      header.children.each_with_index do |column, index|
        accident[column.text] = row.children[index].text if column.text.strip != ""
      end
      f.write(accident.to_json + ",\n")
    end

    puts page_count
  end
  f.write("]")
  f.close
end

desc "Geocode accidents data"
task :geocode do
  json = File.read("accidents.json")
  f = File.open("accidents_geocoded.json", "w")
  f.write("[")
  jsons = JSON.parse(json)
  count = 0
  jsons.each_with_index do |json, index|
#    if index > 1797
      query = "#{json["Street1"]} and #{json["Street2"]}, San Francisco"
      #result = Geocoder.search(query)
      result = Geokit::Geocoders::GoogleGeocoder.geocode(query)
      if result
        #json.merge!(result[0].data["geometry"]["location"])
        json.merge!({"lat" => result.lat, "lng" => result.lng})
        f.write(json.to_json + ",\n")
        puts query
        puts json
        sleep(0.75)
      end
#    end
  end

  f.write("]")
  f.close
end

desc "Populate accident data to database"
task :populate do
  jsons = JSON.parse(File.read("accidents_geocoded.json"))
#  jsons = JSON.parse(File.read("test_accidents.json"))
  coll = $db["accidents"]
  coll.drop
  jsons.each do |json|
    coll.insert(json.merge({"loc" => {"lat" => json["lat"], "lng" => json["lng"]}}))
  end
  $db["accidents"].ensure_index([["loc","2d"]])
end
